default_agent: fsi_websearch_mcp
agents:
  fsi_websearch_mcp:
    name: fsi_websearch_mcp
    language: python
    node_version: null
    entrypoint: /Users/zohaibso/AI Workshops/FSI-AgentCore-Workshop/04-agentcore-runtime-mcp/mcp_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::905035168378:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-f4993fa5e3
      execution_role_auto_create: false
      account: '905035168378'
      region: ap-southeast-2
      ecr_repository: 905035168378.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-fsi_websearch_mcp
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: fsi_websearch_mcp-Odq9bg3tKv
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:905035168378:runtime/fsi_websearch_mcp-Odq9bg3tKv
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-fsi_websearch_mcp-builder
      execution_role: arn:aws:iam::905035168378:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-f4993fa5e3
      source_bucket: bedrock-agentcore-codebuild-sources-905035168378-ap-southeast-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 7kfb0q50sikcij5tioeap0h5vo
        discoveryUrl: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_F1YwHUzhc/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
